
title: TopoInVis 2024
email: topoinvis@ieeevis.org
baseurl: ""
url: "http://topoinvis.org"

# --- site config ---

description: > 
  IEEE Workshop on Topological Data Analysis and Visualization, in conjunction with IEEE VIS 2024, Florida, USA

navigation:
 - title: Home
   url: index.html
 - title: Program
   url: program.html
 - title: Call for Papers
   url: call-for-papers.html
 - title: Submission
   url: submission.html
 - title: Accepted Papers
   url: accepted-papers.html
 - title: Awards
   url: awards.html
 - title: Organization
   url: organization.html

# --- end site config ---

# build settings
markdown: kramdown

plugins: 
#  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - misc
  - archive/previous
  - s3_website.yml
  - .travis.yml
  - vendor

collections: 
  pages:
    output: true
    permalink: /:path:output_ext


#theme: jekyll-theme-cayman
